# Server
server.port=8080

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/spondclub
spring.datasource.username=spond
spring.datasource.password=spond123

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG